import { OrderType } from '../../services/apiOrder.ts';

export const mockEmptyOrders = [];

export const mockOrders: OrderType[] = [
  {
    created_at: '2025-02-26T20:45:04.66955+00:00',
    paymentMethod: 'paypal',
    paymentStatus: 'paid',
    customer_id: '9',
    cart: {
      id: '8',
      items: [
        {
          name: 'Chicken Sausage',
          price: 284,
          item_id: 16,
          currency: 'Kč‎',
          imageUrl: '',
          quantity: 1,
          rowTotal: 284,
          description:
            'Molten Cheese Indulgence with American classic herbed chicken sausage',
          maxOrderQuantity: 10,
        },
        {
          name: 'Golden Corn',
          price: 79,
          item_id: 7,
          currency: 'Kč‎',
          imageUrl: '',
          quantity: 1,
          rowTotal: 79,
          description: 'Sweet & juicy golden corn for that lipsmacking taste',
          maxOrderQuantity: 10,
        },
        {
          name: 'Indi Tandoori Paneer Pizza',
          price: 319,
          item_id: 5,
          currency: 'Kč‎',
          imageUrl: '',
          quantity: 1,
          rowTotal: 319,
          description:
            'It is hot. It is spicy. It is oh-so-Indian. Tandoori paneer with capsicum, red paprika & mint mayo.',
          maxOrderQuantity: 10,
        },
        {
          name: 'Fiery Jalapeno & Paprika',
          price: 199,
          item_id: 8,
          currency: 'Kč‎',
          imageUrl: '',
          quantity: 1,
          rowTotal: 199,
          description:
            'Spiciest veg pizza with jalapeno & red paprika toppings and a new spicy peri peri sauce.',
          maxOrderQuantity: 10,
        },
      ],
      currency: 'Kč‎',
      isActive: true,
      itemsCount: 4,
      cartSummary: {
        vat: 88.1,
        subtotal: 881,
        grandTotal: 974.1,
        deliveryCost: 5,
        discountAmount: 0,
        vatRatePercentage: 10,
        discountPercentage: 0,
      },
      customer_id: '9',
      itemsQuantity: 4,
    },
    customer: {
      id: '9',
      role: 'customer',
      uuid: '6edb8307-47c4-40d8-b8a2-d197e5b82ba1',
      avatar: '',
      cart_id: '8',
      lastName: 'lastName',
      metaData: {
        sub: '',
        role: 'customer',
        email: 'charan@example.com',
        lastName: 'lastName',
        firstName: 'firstName',
        emailAddress: 'charan@example.com',
        email_verified: true,
        phone_verified: false,
      },
      addresses: [],
      firstName: 'firstName',
      emailAddress: 'charan@example.com',
      defaultBilling: '',
      defaultShipping: '',
    },
    deliveryAddress: {
      id: '10',
      city: 'city',
      pinCode: '123456',
      landmark: '',
      lastName: 'lastName',
      firstName: 'firstName',
      customer_id: "9",
      phoneNumber: '+49 1578 7941234',
      emailAddress: 'charan@example.com',
      houseAddress: 'house address',
      useForBilling: false,
      deliveryAddress: true,
    },
    id: '10',
    deliveryStatus: 'Processing',
    orderStatus: 'complete',
  },
];
